apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  annotations:
    create-external-hub-kubeconfig: "2026-03-19T14:49:58Z"
  labels:
    hypershift.openshift.io/auto-created-for-infra: demo-hl7tn
  name: demo
  namespace: local-cluster
spec:
  clusterID: fb7cfc30-eac0-4b45-a163-df42a54c107e
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: sandbox5342.opentlc.com
    privateZoneID: Z01444371GM9JTOFFEB8
    publicZoneID: Z01862502ESLGVO54794O
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: demo-hl7tn
  infrastructureAvailabilityPolicy: SingleReplica
  issuerURL: https://oidc-storage-hl7tn.s3.us-east-2.amazonaws.com/demo-hl7tn
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    machineNetwork:
    - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-0dc056e436e2f706d
        vpc: vpc-051ce05d962dfb62f
        zone: us-west-2b
      endpointAccess: Public
      region: us-west-1
      resourceTags:
      - key: kubernetes.io/cluster/demo-hl7tn
        value: owned
      rolesRef:
        controlPlaneOperatorARN: arn:aws:iam::039612890667:role/demo-hl7tn-control-plane-operator
        imageRegistryARN: arn:aws:iam::039612890667:role/demo-hl7tn-openshift-image-registry
        ingressARN: arn:aws:iam::039612890667:role/demo-hl7tn-openshift-ingress
        kubeCloudControllerARN: arn:aws:iam::039612890667:role/demo-hl7tn-cloud-controller
        networkARN: arn:aws:iam::039612890667:role/demo-hl7tn-cloud-network-config-controller
        nodePoolManagementARN: arn:aws:iam::039612890667:role/demo-hl7tn-node-pool
        storageARN: arn:aws:iam::039612890667:role/demo-hl7tn-aws-ebs-csi-driver-controller
    type: AWS
  pullSecret:
    name: demo-pull-secret
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
  secretEncryption:
    aescbc:
      activeKey:
        name: demo-etcd-encryption-key
    type: aescbc
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: demo-ssh-key
