apiVersion: v1
items:
- apiVersion: hypershift.openshift.io/v1beta1
  kind: HostedCluster
  metadata:
    annotations:
      create-external-hub-kubeconfig: "2026-03-18T10:53:31Z"
    labels:
      hypershift.openshift.io/auto-created-for-infra: dev-hl7tn
    name: development
    namespace: local-cluster
  spec:
    clusterID: 4d7f6ad6-edc0-4bc0-8962-b5ed99ff82c3
    controllerAvailabilityPolicy: SingleReplica
    dns:
      baseDomain: sandbox5342.opentlc.com
      privateZoneID: Z03067323FY67BBC8LGXL
      publicZoneID: Z01862502ESLGVO54794O
    etcd:
      managed:
        storage:
          persistentVolume:
            size: 8Gi
            storageClassName: gp3-csi
          type: PersistentVolume
      managementType: Managed
    fips: false
    infraID: dev-hl7tn
    infrastructureAvailabilityPolicy: SingleReplica
    issuerURL: https://oidc-storage-hl7tn.s3.us-east-2.amazonaws.com/dev-hl7tn
    networking:
      clusterNetwork:
      - cidr: 10.132.0.0/14
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OVNKubernetes
      serviceNetwork:
      - cidr: 172.31.0.0/16
    olmCatalogPlacement: management
    platform:
      aws:
        cloudProviderConfig:
          subnet:
            id: subnet-086631da632dfca49
          vpc: vpc-08c703c1a7d947f2e
          zone: us-west-2a
        endpointAccess: Public
        region: us-west-2
        resourceTags:
        - key: kubernetes.io/cluster/dev-hl7tn
          value: owned
        rolesRef:
          controlPlaneOperatorARN: arn:aws:iam::039612890667:role/dev-hl7tn-control-plane-operator
          imageRegistryARN: arn:aws:iam::039612890667:role/dev-hl7tn-openshift-image-registry
          ingressARN: arn:aws:iam::039612890667:role/dev-hl7tn-openshift-ingress
          kubeCloudControllerARN: arn:aws:iam::039612890667:role/dev-hl7tn-cloud-controller
          networkARN: arn:aws:iam::039612890667:role/dev-hl7tn-cloud-network-config-controller
          nodePoolManagementARN: arn:aws:iam::039612890667:role/dev-hl7tn-node-pool
          storageARN: arn:aws:iam::039612890667:role/dev-hl7tn-aws-ebs-csi-driver-controller
      type: AWS
    pullSecret:
      name: development-pull-secret
    release:
      image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
    secretEncryption:
      aescbc:
        activeKey:
          name: development-etcd-encryption-key
      type: aescbc
    services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
    - service: OVNSbDb
      servicePublishingStrategy:
        type: Route
    sshKey:
      name: development-ssh-key
kind: List
metadata:
  resourceVersion: ""
