apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  annotations:
    create-external-hub-kubeconfig: '2026-03-20T12:39:36Z'
  creationTimestamp: '2026-03-20T12:36:35Z'
  finalizers:
  - hypershift.openshift.io/finalizer
  - hypershift.io/aws-oidc-discovery
  generation: 3
  labels:
    hypershift.openshift.io/auto-created-for-infra: demo2-hl7tn
  name: demo2
  namespace: local-cluster
  resourceVersion: '2600736'
  uid: c5bfd828-8de1-4023-b849-691bfcd7e6e7
spec:
  autoscaling: {}
  clusterID: f7e68b72-1d86-4541-9d60-1e4f779390eb
  configuration: {}
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: sandbox5342.opentlc.com
    privateZoneID: Z0440208HAJKP8ILDAWG
    publicZoneID: Z01862502ESLGVO54794O
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: gp3-csi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: demo2-hl7tn
  infrastructureAvailabilityPolicy: SingleReplica
  issuerURL: https://oidc-storage-hl7tn.s3.us-east-2.amazonaws.com/demo2-hl7tn
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    machineNetwork:
    - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: subnet-04a64178d48f989f2
        vpc: vpc-0458919f04f00b23f
        zone: us-west-2a
      endpointAccess: Public
      region: us-west-2
      resourceTags:
      - key: kubernetes.io/cluster/demo2-hl7tn
        value: owned
      rolesRef:
        controlPlaneOperatorARN: arn:aws:iam::039612890667:role/demo2-hl7tn-control-plane-operator
        imageRegistryARN: arn:aws:iam::039612890667:role/demo2-hl7tn-openshift-image-registry
        ingressARN: arn:aws:iam::039612890667:role/demo2-hl7tn-openshift-ingress
        kubeCloudControllerARN: arn:aws:iam::039612890667:role/demo2-hl7tn-cloud-controller
        networkARN: arn:aws:iam::039612890667:role/demo2-hl7tn-cloud-network-config-controller
        nodePoolManagementARN: arn:aws:iam::039612890667:role/demo2-hl7tn-node-pool
        storageARN: arn:aws:iam::039612890667:role/demo2-hl7tn-aws-ebs-csi-driver-controller
    type: AWS
  pullSecret:
    name: demo2-pull-secret
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
  secretEncryption:
    aescbc:
      activeKey:
        name: demo2-etcd-encryption-key
    type: aescbc
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: demo2-ssh-key
