apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  labels:
    hypershift.openshift.io/auto-created-for-infra: demo-hl7tn
  name: demo-us-west-2a
  namespace: local-cluster
spec:
  arch: amd64
  clusterName: demo
  management:
    autoRepair: true
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    aws:
      # Replace with the instance profile provisioned for the demo infraID
      instanceProfile: demo-hl7tn-worker
      instanceType: m6a.2xlarge
      rootVolume:
        size: 120
        type: gp3
      securityGroups:
        # Replace with the security group ID provisioned for the demo cluster
      # - id: <demo-security-group-id>
      subnet:
        # Replace with the subnet ID for the demo cluster
        # id: <demo-subnet-id>
    type: AWS
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
  replicas: 1
