apiVersion: v1
items:
- apiVersion: hypershift.openshift.io/v1beta1
  kind: NodePool
  metadata:
    annotations:
      hypershift.openshift.io/nodePoolCurrentConfig: 3f01dacf
      hypershift.openshift.io/nodePoolCurrentConfigVersion: eb5c0a6f
      hypershift.openshift.io/nodePoolPlatformMachineTemplate: demo-us-west-2a-a83aa1ca
    labels:
      hypershift.openshift.io/auto-created-for-infra: demo-hl7tn
    name: demo-us-west-2a
    namespace: local-cluster
  spec:
    arch: amd64
    clusterName: demo
    management:
      autoRepair: true
      replace:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        strategy: RollingUpdate
      upgradeType: Replace
    nodeDrainTimeout: 0s
    platform:
      aws:
        instanceProfile: demo-hl7tn-worker
        instanceType: m6a.large
        rootVolume:
          size: 120
          type: gp3
        securityGroups:
        - id: sg-08d0d00ca9a584f3e
        subnet:
          id: subnet-0ffe3fb7b36c4ec87
      type: AWS
    release:
      image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
    replicas: 1
- apiVersion: hypershift.openshift.io/v1beta1
  kind: NodePool
  metadata:
    annotations:
      hypershift.openshift.io/nodePoolCurrentConfig: 31eefb9b
      hypershift.openshift.io/nodePoolCurrentConfigVersion: d8068ccb
      hypershift.openshift.io/nodePoolPlatformMachineTemplate: development-us-west-2a-8561cab0
    labels:
      app.kubernetes.io/instance: hcp-local-cluster
      hypershift.openshift.io/auto-created-for-infra: dev-hl7tn
    name: development-us-west-2a
    namespace: local-cluster
  spec:
    arch: amd64
    clusterName: development
    management:
      autoRepair: true
      replace:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        strategy: RollingUpdate
      upgradeType: Replace
    nodeDrainTimeout: 0s
    platform:
      aws:
        instanceProfile: dev-hl7tn-worker
        instanceType: m6a.2xlarge
        rootVolume:
          size: 120
          type: gp3
        securityGroups:
        - id: sg-0e70c012f923c62fa
        subnet:
          id: subnet-086631da632dfca49
      type: AWS
    release:
      image: quay.io/openshift-release-dev/ocp-release:4.14.3-x86_64
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
