---
# AppProject: argocd-dev
#
# Scopes what the argocd-dev Applications are allowed to deploy and where.
# Specifically used to manage the ArgoCD instance in the coffeeshop-gitops
# namespace on the coffeeshop spoke cluster.
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-dev
  namespace: openshift-gitops
spec:
  description: Project for deploying and managing ArgoCD instances on dev spoke clusters
  sourceRepos:
    - https://github.com/froberge/acm_hcp_argocd_demo
  destinations:
    - name: coffeeshop
      namespace: coffeeshop-gitops
    - name: coffeeshop
      namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: ArgoCD
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: route.openshift.io
      kind: Route
