apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acm-placement-configmap.yaml
  - gitopscluster-rbac.yaml
  - argocd-hypershift-rbac.yaml
  - managedclustersetbinding.yaml
  - placement.yaml
  - gitopscluster.yaml
  - appproject.yaml
  - applicationset.yaml
  - app-acm-policies.yaml
